### ISSUE TITLE
【バグ】概要欄に改行タグが含まれる場合にエラーが出る【gurutabi_crawler】

### ISSUE THREAD

**Issue by kzysd** [clams2017/TravelPlan#2]
【事象】

スポット詳細ページの概要欄に改行タグ (`<br>`) が含まれる場合、GurutabiSpot.descriptionがNoneになり、OreoreSpotへの変換時にエラーが発生する。

```
$ ./gurutabi_clawler.py 
fetch list: https://gurutabi.gnavi.co.jp/i/d03/gs20601/
fetch spot: https://gurutabi.gnavi.co.jp/i/i_53900/
fetch spot: https://gurutabi.gnavi.co.jp/i/i_44192/
fetch spot: https://gurutabi.gnavi.co.jp/i/i_58083/
fetch spot: https://gurutabi.gnavi.co.jp/i/i_1001472/
Traceback (most recent call last):
  File "./gurutabi_clawler.py", line 131, in <module>
    main()
  File "./gurutabi_clawler.py", line 22, in main
    results = crawl(target, storer)
  File "./gurutabi_clawler.py", line 44, in crawl
    spots.append(spot.convert(id))
  File "/Users/yoshida/IdeaProjects/TravelPlan/scraping/GurutabiSpot.py", line 23, in convert
    self.access_text
  File "/Users/yoshida/IdeaProjects/TravelPlan/scraping/OreoreSpot.py", line 5, in __init__
    self.description = description[:128]
TypeError: 'NoneType' object is not subscriptable
```

https://gurutabi.gnavi.co.jp/i/i_1001472/

```
楽しさいっぱいのまちだリス園です。<br>
<br>
一番は、放し飼いのリストとのふれあいが楽しめます。<br>
（フェンスで囲まれた外周200ｍの広場に約200匹のタイワンリスが放し飼いされていて、<br>
自由にエサ（ヒマワリの種）をあげることができます。（１袋１００円））<br>
<br>
また、モルモット、ウサギなど小動物をひざの上に抱いて、癒しの時間が楽しめます。<br>
可愛らしいプレーリードックなどの珍しい小動物の見学も楽しめます。
```

【原因】

`<p>`タグ内に`<br>`が含まれると`find('p').string`でテキストを取得できないため。

https://github.com/clams2017/TravelPlan/blob/3d03b3582d7d65c2e5ddcd1abd1349ff3038e206/scraping/gurutabi_clawler.py#L83-L89

【対応】

`find('p').strings`を利用する。

**Comment by kzysd** [comment]
132d969582a8f41c40ee9414846fda34fe57b252
